@startuml

scale 800 width

top to bottom direction
skinparam linetype ortho

class attendee_type {
   description: varchar(255)
   attendee_type_name: varchar(255)
   + {static} attendee_type_id: bigint
}
class position {
   description: varchar(255)
   position_name: varchar(255)
   + {static} position_id: bigint
}
class program_syllabus {
   uuid: uuid
   + {static} training_program_id: bigint
   + {static} id: bigint
}
class technical_code {
   description: varchar(255)
   technical_code_name: varchar(255)
   + {static} technical_code_id: bigint
}
class technical_group {
   description: varchar(255)
   technical_group_name: varchar(255)
   + {static} technical_group_id: bigint
}
class training_program {
   created_by: varchar(255)
   created_date: timestamp
   updated_by: varchar(255)
   updated_date: timestamp
   uuid: uuid
   code: varchar(255)
   days: integer
   hours: integer
   issued_date: timestamp
   issued_status: varchar(255)
   name: varchar(255)
   status: integer
   + {static} attendee_id: bigint
   + {static} position_id: bigint
   + {static} technical_code_id: bigint
   + {static} technical_group_id: bigint
   + {static} id: bigint
}

program_syllabus  -[plain]-^  training_program : "training_program_id:id"
training_program  -[plain]-^  attendee_type    : "attendee_id:attendee_type_id"
training_program  -[plain]-^  position         : "position_id"
training_program  -[plain]-^  technical_code   : "technical_code_id"
training_program  -[plain]-^  technical_group  : "technical_group_id"
@enduml
